### ISSUE TITLE
add base url for cypress test routes

### ISSUE THREAD

**Issue by minju25kim** [fac24/week2-alex-maria-peter-sonia#24]
https://github.com/fac24/week2-alex-maria-peter-sonia/blob/de4b47cd1cdfa373333402d36fdf125bf57bc6bb/cypress.json#L1

if you test a lot of routes in cypress then you can add baseurl in cypress.json file.

and add route in cypress>intergration>tests.js , that already includes your baseURL.

**Comment by sonianb** [comment]
Will do that. Thank you for the suggestion!
